# Generated by Django 3.2.8 on 2021-10-12 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Agenda_Zero_ILumi_Core_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento_agendado',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento_agendado',
            name='data_da_criacao_do_evento_agendado',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='evento_agendado',
            name='data_do_evento_agendado',
            field=models.DateTimeField(verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='evento_agendado',
            name='decricao_do_evento_agendado',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='evento_agendado',
            name='titulo_do_evento_agendado',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
