# Generated by Django 3.2.8 on 2021-10-12 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento_Agendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_do_evento_agendado', models.CharField(max_length=100, verbose_name='Titulo')),
                ('decricao_do_evento_agendado', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_do_evento_agendado', models.DateTimeField(verbose_name='Data do Evento')),
                ('data_da_criacao_do_evento_agendado', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Eventos Agendados',
            },
        ),
    ]
