# Generated by Django 3.2.8 on 2021-10-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zero_ilumi_agenda_core', '0002_evento_agendado_local_do_evento_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento_agendado',
            name='epoca_do_ano',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Epoca do Ano'),
        ),
    ]
